[version]
source = "regex"
scheme = "standard"
path = "src/{{ cookiecutter.project_slug }}/__init__.py"

[build]
reproducible = true
directory = "dist"
dev-mode-dirs = ["src"]

[envs.virtual]
python = {{ cookiecutter.python_version }}
platforms = ["linux", "windows", "macos"]

[tool.hatch.metadata]
allow-direct-references = true
allow-ambiguous-features = true
# EDIT THESE IF NEEDED